In [103]:
import pandas as pd #데이터분석
import numpy as np #행렬이나 일반적으로 대규모 다차원 배열을 처리
import matplotlib as mpl
import matplotlib.pyplot as plt
import datetime #타임스탬프가 특정시간으로나오게

In [104]:
data = pd.read_excel('data.xlsx')#연습용xlsx
#data = pd.read_excel('O_Retail.xlsx')
data[0:]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
4,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850,United Kingdom
5,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047,United Kingdom
6,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047,United Kingdom
7,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047,United Kingdom

In [130]:
#여기서부터 다시 수정하기

value=[]
value1=[]
value2=[]
dir={}

No = data['InvoiceNo']
for i in range(0,len(No)):
    value2.append(data['StockCode'][i])
    value2.append(data['Description'][i])
    value2.append(data['Quantity'][i])
    value2.append(data['UnitPrice'][i])
    if (i == len(No)-1) or (No[i] != No[i+1]):
        value.append(data['InvoiceDate'][i])
        value.append(data['CustomerID'][i])
        value.append(data['Country'][i])
        dir[No[i]]=value+[value2]
        print(No[i],dir[No[i]])
        value2=[]
        print()
    else:
        pass;

#print(dir[No[1]][0])

536365 [Timestamp('2010-12-01 08:26:00'), 17850, 'United Kingdom', ['85123A', 'WHITE HANGING HEART T-LIGHT HOLDER', 6, 2.55, 71053, 'WHITE METAL LANTERN', 6, 3.39, '84406B', 'CREAM CUPID HEARTS COAT HANGER', 8, 2.75]]

536366 [Timestamp('2010-12-01 08:26:00'), 17850, 'United Kingdom', Timestamp('2010-12-01 08:28:00'), 17850, 'United Kingdom', [22633, 'HAND WARMER UNION JACK', 6, 1.85, 22632, 'HAND WARMER RED POLKA DOT', 6, 1.85]]

536367 [Timestamp('2010-12-01 08:26:00'), 17850, 'United Kingdom', Timestamp('2010-12-01 08:28:00'), 17850, 'United Kingdom', Timestamp('2010-12-01 08:34:00'), 13047, 'United Kingdom', [84879, 'ASSORTED COLOUR BIRD ORNAMENT', 32, 1.69, 22745, "POPPY'S PLAYHOUSE BEDROOM ", 6, 2.1, 22748, "POPPY'S PLAYHOUSE KITCHEN", 6, 2.1]]